[package]
name = "genuary-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.*"

[[bin]]
name = "hello"
path = "src/bin/hello.rs"

[[bin]]
name = "01"
path = "src/bin/01.rs"
